### ISSUE TITLE
ZYLYTY

### ISSUE THREAD

**Issue by ZYLYTY** [cpfergus1/zylytyPractice#1]
Hello @cpfergus1,

Thank you for submitting your challenge to us.

You are receiving this message because we found the score of your project quite low, which usually triggers some alerts in our system that highlight the possibility of your submission having been unfairly scored by our system.

I will be putting here some findings so we can try to reach a fairer score. 😃

**Comment by ZYLYTY** [comment]
We started by assessing your ENVs, to make sure they were being injected to your runtime container, but we found an issue:

![image](https://github.com/cpfergus1/zylytyPractice/assets/154766188/74c824ec-e5bc-42a9-bbcb-0a0facff89ce)

As you can see the port to listen is set to `4000`, and your app is being able to get it perfectly as you can see here:

![image](https://github.com/cpfergus1/zylytyPractice/assets/154766188/3b7c8178-9f67-45fd-a983-8bbc72af084a)

Although you can perfectly see the ENV, for some reason your server is still assuming port 3000.

**Comment by ZYLYTY** [comment]
Another issue we found is that your server is creating two additional databases:

![image](https://github.com/cpfergus1/zylytyPractice/assets/154766188/31fe6c95-72c8-4269-b5db-5bfdfdec1670)

But the objective is to just use the one provided to you via the env `DB_SCHEMA_NAME`, otherwise the tests will fail.

**Comment by FeatureSpitter** [comment]
The registration endpoint is failing with a basic request:

![image](https://github.com/cpfergus1/zylytyPractice/assets/39516190/1d00a07c-09f5-406d-b8bf-cfe594033364)

```
$ curl -X POST "http://localhost:8080/user/register"      -H "Content-Type: application/json"      -d '{
           "username": "fakeuser123",
           "password": "yourSecurePassword",
           "email": "fakeuser123@example.com"
         }'
```

Both this endpoint and the login one are critical for everything else to be tested properly. This is probably the major reason why your functionality tests all failed.

**Comment by ZYLYTY** [comment]
The registration endpoint is failing with a basic request:

![image](https://github.com/cpfergus1/zylytyPractice/assets/39516190/1d00a07c-09f5-406d-b8bf-cfe594033364)

```
$ curl -X POST "http://localhost:8080/user/register"      -H "Content-Type: application/json"      -d '{
           "username": "fakeuser123",
           "password": "yourSecurePassword",
           "email": "fakeuser123@example.com"
         }'
```

Both this endpoint and the login one are critical for everything else to be tested properly. This is probably the major reason why your functionality tests all failed.

**Comment by ZYLYTY** [comment]
Please let us know when you fix these issues, so we can re-fetch your submission for evaluation.

Thanks.

**Comment by cpfergus1** [comment]
Thanks for reaching out!

I have corrected the server errors with [#91e19e](https://github.com/cpfergus1/zylytyPractice/commit/91e19e92728ec4066f2733976e66c365063f598e) and corrected the user controller errors by removing a before hook which was left in after attempting to clean my commits 😓 

The server errors were caused by overwriting my binding in puma config when executing rails in Dockerfile and two database schemas were being created because in the [development environment](https://github.com/rails/rails/blob/8e46af8c9396e731aaf5269182138c22621a7aa0/activerecord/lib/active_record/railties/databases.rake#L44) that is default. 

It looks to be working now I and accept my fate on the eval 😄

**Comment by ZYLYTY** [comment]
Hello @cpfergus1 we are witnessing these error logs:

```
ruby_1        | rails aborted!
ruby_1        | ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)
ruby_1        | 
ruby_1        |         raise ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment, set this string with `bin/rails credentials:edit`"
ruby_1        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ruby_1        | /app/config/environment.rb:5:in `<main>'
ruby_1        | Tasks: TOP => db:prepare => db:load_config => environment
ruby_1        | (See full trace by running task with --trace)
zylytypractice_ruby_1 exited with code 1
```

Maybe some config is missing on rails?

**Comment by cpfergus1** [comment]
Yeah, I put up another commit that should fix that but I want to test on another machine before asking you to check again, I will reply shortly

**Comment by ZYLYTY** [comment]
Try running directly with the docker container, which is the closest to the environment where it will be tested in ZYLYTY.

**Comment by cpfergus1** [comment]
> Try running directly with the docker container, which is the closest to the environment where it will be tested in ZYLYTY.

My containers on my machine are green, I am not 100% sure why you are getting this error and I think I fixed it, but I want to test it on another machine before you do 😄

![image](https://github.com/cpfergus1/zylytyPractice/assets/68167430/16335463-6c79-4a20-8074-9eded91a5015)

![image](https://github.com/cpfergus1/zylytyPractice/assets/68167430/589caa5c-14e4-4668-88c1-51b0efed9383)

**Comment by ZYLYTY** [comment]
Can you try running this docker-compose.yaml in the root of your project?

```yaml
version: '3.8'

services:
  ruby:
    build: .
    ports:
      - "8080:4000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: test
      DB_SCHEMA_NAME: main_db
      DB_PORT: 5432
      DB_HOST: postgresdb  # Use the service name as the host within Docker network
      ADMIN_API_KEY: DEFAULT-API-KEY
      API_LISTENING_PORT: 4000
    depends_on:
      - postgresdb
    networks:
      - app-network

  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"  # Optional: Expose PostgreSQL port on the host for direct access
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
```

With:
`docker-compose down && docker-compose build && docker-compose up`
